spring:
    profiles:
        active: prod
    cache:
        type: SIMPLE
    servlet:
        multipart:
            max-file-size: 10MB

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            id-type: AUTO
    mapper-locations: classpath:/mapper/*.xml

server:
    compression:
        enabled: true
        mime-types: text/css,application/javascript
    error:
        include-message: always

